"""FileStoragePort — an outbound port for storing raw uploaded files.

The application layer defines this abstraction. The infrastructure layer
implements it (local disk for now; swappable for object storage later
without touching a single use case). Callers address files only by an
opaque `storage_key` generated by the caller — never by a user-supplied
filename — so a leaked key can't be traced back to who uploaded what.
"""

from __future__ import annotations

from abc import ABC, abstractmethod


class FileStoragePort(ABC):
    """Persists and retrieves raw file bytes by opaque storage key."""

    @abstractmethod
    async def save(self, storage_key: str, content: bytes) -> None:
        """Durably store `content` under `storage_key`."""

    @abstractmethod
    async def delete(self, storage_key: str) -> None:
        """Remove the file stored under `storage_key`, if any."""
